version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - /var/lib/sqlite3:/root/CourseWork7/CourseWork7.db
    healthcheck:
        test: ["CMD-SHELL"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'
    volumes:
      - .:/code

  celery:
    build: .
    tty: true
    command: celery -A CourseWork7 worker -l INFO
    depends_on:
      - redis
      - app
  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A CourseWork7 beat -l INFO -S django
    depends_on:
      - redis
      - app
volumes:
  pgdata: