# Generated by Django 4.2.4 on 2023-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность'),
        ),
    ]
