# Generated by Django 4.2.4 on 2023-09-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_delete_mailing_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.TimeField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
    ]
